require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BenchPressDataPointsController do

  # This should return the minimal set of attributes required to create a valid
  # BenchPressDataPoint. As you add validations to BenchPressDataPoint, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BenchPressDataPointsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all bench_press_data_points as @bench_press_data_points" do
      bench_press_data_point = BenchPressDataPoint.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bench_press_data_points).should eq([bench_press_data_point])
    end
  end

  describe "GET show" do
    it "assigns the requested bench_press_data_point as @bench_press_data_point" do
      bench_press_data_point = BenchPressDataPoint.create! valid_attributes
      get :show, {:id => bench_press_data_point.to_param}, valid_session
      assigns(:bench_press_data_point).should eq(bench_press_data_point)
    end
  end

  describe "GET new" do
    it "assigns a new bench_press_data_point as @bench_press_data_point" do
      get :new, {}, valid_session
      assigns(:bench_press_data_point).should be_a_new(BenchPressDataPoint)
    end
  end

  describe "GET edit" do
    it "assigns the requested bench_press_data_point as @bench_press_data_point" do
      bench_press_data_point = BenchPressDataPoint.create! valid_attributes
      get :edit, {:id => bench_press_data_point.to_param}, valid_session
      assigns(:bench_press_data_point).should eq(bench_press_data_point)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BenchPressDataPoint" do
        expect {
          post :create, {:bench_press_data_point => valid_attributes}, valid_session
        }.to change(BenchPressDataPoint, :count).by(1)
      end

      it "assigns a newly created bench_press_data_point as @bench_press_data_point" do
        post :create, {:bench_press_data_point => valid_attributes}, valid_session
        assigns(:bench_press_data_point).should be_a(BenchPressDataPoint)
        assigns(:bench_press_data_point).should be_persisted
      end

      it "redirects to the created bench_press_data_point" do
        post :create, {:bench_press_data_point => valid_attributes}, valid_session
        response.should redirect_to(BenchPressDataPoint.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bench_press_data_point as @bench_press_data_point" do
        # Trigger the behavior that occurs when invalid params are submitted
        BenchPressDataPoint.any_instance.stub(:save).and_return(false)
        post :create, {:bench_press_data_point => { "user_id" => "invalid value" }}, valid_session
        assigns(:bench_press_data_point).should be_a_new(BenchPressDataPoint)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BenchPressDataPoint.any_instance.stub(:save).and_return(false)
        post :create, {:bench_press_data_point => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bench_press_data_point" do
        bench_press_data_point = BenchPressDataPoint.create! valid_attributes
        # Assuming there are no other bench_press_data_points in the database, this
        # specifies that the BenchPressDataPoint created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BenchPressDataPoint.any_instance.should_receive(:update_attributes).with({ "user_id" => "1" })
        put :update, {:id => bench_press_data_point.to_param, :bench_press_data_point => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested bench_press_data_point as @bench_press_data_point" do
        bench_press_data_point = BenchPressDataPoint.create! valid_attributes
        put :update, {:id => bench_press_data_point.to_param, :bench_press_data_point => valid_attributes}, valid_session
        assigns(:bench_press_data_point).should eq(bench_press_data_point)
      end

      it "redirects to the bench_press_data_point" do
        bench_press_data_point = BenchPressDataPoint.create! valid_attributes
        put :update, {:id => bench_press_data_point.to_param, :bench_press_data_point => valid_attributes}, valid_session
        response.should redirect_to(bench_press_data_point)
      end
    end

    describe "with invalid params" do
      it "assigns the bench_press_data_point as @bench_press_data_point" do
        bench_press_data_point = BenchPressDataPoint.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BenchPressDataPoint.any_instance.stub(:save).and_return(false)
        put :update, {:id => bench_press_data_point.to_param, :bench_press_data_point => { "user_id" => "invalid value" }}, valid_session
        assigns(:bench_press_data_point).should eq(bench_press_data_point)
      end

      it "re-renders the 'edit' template" do
        bench_press_data_point = BenchPressDataPoint.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BenchPressDataPoint.any_instance.stub(:save).and_return(false)
        put :update, {:id => bench_press_data_point.to_param, :bench_press_data_point => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bench_press_data_point" do
      bench_press_data_point = BenchPressDataPoint.create! valid_attributes
      expect {
        delete :destroy, {:id => bench_press_data_point.to_param}, valid_session
      }.to change(BenchPressDataPoint, :count).by(-1)
    end

    it "redirects to the bench_press_data_points list" do
      bench_press_data_point = BenchPressDataPoint.create! valid_attributes
      delete :destroy, {:id => bench_press_data_point.to_param}, valid_session
      response.should redirect_to(bench_press_data_points_url)
    end
  end

end
